import { 
  Baby, 
  GraduationCap, 
  UserRound, 
  Users,
  MessageSquare
} from 'lucide-react';
import { User } from './types';

export const ICON_MAP: Record<string, any> = {
  Baby,
  GraduationCap,
  UserRound,
  Users,
  MessageSquare
};

export const ARABIC_MONTHS = [
  'يناير', 'فبراير', 'مارس', 'أبريل', 'مايو', 'يونيو',
  'يوليو', 'أغسطس', 'سبتمبر', 'أكتوبر', 'نوفمبر', 'ديسمبر'
];

export const TRANSLATIONS = {
  ar: {
    churchName: 'مدارس الأحد',
    churchSubName: 'مارجرجس و الأنبا باخوميوس',
    dashboard: 'لوحة التحكم',
    servants: 'الخدام',
    attendance: 'الحضور والغياب',
    trips: 'الرحلات',
    settings: 'الإعدادات',
    logout: 'تسجيل الخروج',
    agenda: 'أجندة الأعياد',
    export: 'تصدير البيانات (CSV)',
    import: 'استيراد البيانات',
    profile: 'الملف الشخصي',
    admin: 'مدير',
    priest: 'أب كاهن',
    serviceLeader: 'أمين خدمة',
    servant: 'خادم',
    back: 'رجوع',
    save: 'حفظ',
    cancel: 'إلغاء',
    edit: 'تعديل',
    delete: 'حذف',
    search: 'بحث...',
    language: 'اللغة',
    darkMode: 'الوضع الليلي',
    readingMode: 'وضع القراءة',
    fontSize: 'حجم الخط',
    fontFamily: 'شكل الخط',
    dateTimeSettings: 'إعدادات الوقت والتاريخ',
    dateFormat: 'تنسيق التاريخ',
    timeFormat: 'تنسيق الوقت',
    male: 'ذكر',
    female: 'أنثى',
    all: 'الكل',
    mass: 'القداس',
    service: 'الخدمة',
    notes: 'ملاحظات',
    birthDate: 'تاريخ الميلاد',
    phone: 'التليفون',
    address: 'العنوان',
    confession: 'أب الاعتراف',
    father: 'الأب',
    mother: 'الأم',
    job: 'الوظيفة',
    whatsapp: 'واتساب',
    facebook: 'فيسبوك',
    telegram: 'تيليجرام',
    instagram: 'إنستجرام',
    gmail: 'جيميل',
    landline: 'تليفون أرضي',
    saveTrip: 'حفظ الرحلة',
    tripName: 'اسم الرحلة',
    tripDate: 'تاريخ الرحلة',
    tripPrice: 'سعر الرحلة',
    bookings: 'الحجوزات',
    amount: 'المبلغ',
    total: 'الإجمالي',
    report: 'تقرير',
    monthly: 'شهري',
    yearly: 'سنوي',
    month: 'الشهر',
    year: 'السنة',
    noData: 'لا توجد بيانات',
    login: 'تسجيل الدخول',
    register: 'إنشاء حساب جديد',
    username: 'اسم المستخدم',
    password: 'كلمة المرور',
    fullName: 'الاسم بالكامل',
    showPassword: 'إظهار كلمة المرور',
    authError: 'خطأ في تسجيل الدخول',
    welcome: 'أهلاً بك',
    copticDate: 'التاريخ القبطي',
    gregorianDate: 'التاريخ الميلادي',
    time: 'الوقت',
    services: 'الخدمات',
    servantsList: 'قائمة الخدام',
    mlayka: 'ملايكة',
    ibtida2y: 'ابتدائي',
    eadady: 'إعدادي',
    thanawy: 'ثانوي',
    shabab: 'شباب',
    birthdaysThisWeek: 'أعياد ميلاد هذا الأسبوع',
    today: 'اليوم!',
    servantsCount: 'مخدوم',
    addServant: 'إضافة مخدوم',
    reports: 'التقارير',
    classStats: 'إحصائيات الفصل',
    registerAttendance: 'تسجيل الحضور',
    add: 'إضافة',
    searchByName: 'ابحث بالاسم...',
    allBirthMonths: 'كل شهور الميلاد',
    noServants: 'لا يوجد مخدومين مضافين بعد في هذا الفصل.',
    tripsFor: 'رحلات',
    addTrip: 'إضافة رحلة',
    viewBookings: 'عرض الحجز',
    price: 'السعر',
    general: 'عامة',
    currency: 'ج.م',
    confirmDeleteTrip: 'حذف الرحلة؟',
    copticFeast: 'عيد قبطي',
    agendaTitle: 'أجندة الأعياد والمناسبات',
    loginButton: 'دخول',
    registerButton: 'تسجيل الحساب',
    noAccount: 'ليس لديك حساب؟ سجل الآن',
    haveAccount: 'لديك حساب بالفعل؟ سجل دخول',
    readingModeDesc: 'تحسين تجربة القراءة',
    fontColor: 'لون الخط',
    fontColorDesc: 'تغيير لون الخط الأساسي',
    darkModeDesc: 'تغيير مظهر التطبيق',
    small: 'صغير',
    medium: 'متوسط',
    large: 'كبير',
    sans: 'عادي',
    serif: 'كلاسيك',
    mono: 'برمجي',
    h12: '12 ساعة',
    h24: '24 ساعة',
    totalCollected: 'إجمالي المحصل',
    totalRemaining: 'إجمالي المتبقي',
    selectServantToBook: 'اختر مخدوم للحجز',
    bookingsList: 'قائمة الحجوزات',
    deletedServant: 'مخدوم محذوف',
    remaining: 'متبقي',
    noBookings: 'لا يوجد حجز بعد',
    tripDayMessage: 'اليوم هو ميعاد الرحلة! القائمة جاهزة.',
    saveAttendance: 'حفظ الحضور',
    backToList: 'العودة للقائمة',
    personalData: 'البيانات الشخصية',
    notSpecified: 'غير محدد',
    call: 'اتصال',
    absenceWarningFather: 'تحذير غياب (الأب)',
    absenceWarningMother: 'تحذير غياب (الأم)',
    whatsappFather: 'واتساب الأب',
    whatsappMother: 'واتساب الأم',
    quickAttendance: 'تسجيل الحضور السريع',
    attendMass: 'حضور القداس',
    attendService: 'حضور الخدمة',
    tripBooking: 'حجز الرحلات',
    paid: 'مدفوع',
    servantsInService: 'الخدام الموجودين في خدماتك',
    assignedServices: 'الخدمات المسندة',
    editServantData: 'تعديل بيانات المخدوم',
    addNewServant: 'إضافة مخدوم جديد',
    servantPhoto: 'صورة المخدوم',
    gender: 'النوع',
    fullNamePlaceholder: 'الاسم ثلاثياً أو رباعياً على الأقل',
    whatsappSameAsPhone: 'نفس رقم الهاتف',
    optional: 'اختياري',
    telegramPlaceholder: 'رقم الهاتف أو اسم المستخدم',
    instagramPlaceholder: 'رابط أو اسم مستخدم',
    gmailPlaceholder: 'البريد الإلكتروني',
    captureCurrentLocation: 'تحديد الموقع الحالي',
    locationCaptured: 'تم تحديد الإحداثيات بنجاح',
    parentsData: 'بيانات الوالدين',
    fatherName: 'اسم الأب',
    fatherJob: 'وظيفة الأب',
    fatherPhone: 'موبايل الأب',
    fatherConfession: 'أب اعتراف الأب',
    motherName: 'اسم الأم',
    motherJob: 'وظيفة الأم',
    motherPhone: 'موبايل الأم',
    motherConfession: 'أب اعتراف الأم',
    servantNotes: 'ملاحظات عن المخدوم',
    servantNotesPlaceholder: 'أضف أي ملاحظات إضافية هنا...',
    saveChanges: 'حفظ التعديلات',
    addServantToService: 'إضافة المخدوم للخدمة',
    select: 'اختر',
    stage: 'المرحلة',
    allStages: 'كل المراحل',
    servantsCountLabel: 'مخدوم',
    backTitle: 'رجوع',
    inThisClass: 'في هذا الفصل',
    noNumber: 'بدون رقم',
    enterAmountAlert: 'برجاء ادخال المبلغ',
    book: 'حجز',
    noTripsAvailable: 'لا يوجد رحلات متاحة حالياً',
    fatherData: 'بيانات الأب',
    motherData: 'بيانات الأم',
    nameLabel: 'الاسم',
    jobLabel: 'الوظيفة',
    notesLabel: 'ملاحظات',
    confirmDeleteServant: 'هل أنت متأكد من حذف هذا المخدوم؟',
    deleteServantPermanently: 'حذف المخدوم نهائياً',
    adminRole: 'مدير النظام',
    priestRole: 'أب كاهن',
    serviceLeaderRole: 'أمين خدمة',
    servantRole: 'خادم',
    fullNameLabel: 'الاسم بالكامل',
    phoneNumberLabel: 'رقم التليفون',
    emailLabel: 'البريد الإلكتروني',
    whatsappLabel: 'واتساب',
    addressLabel: 'العنوان',
    birthDateLabel: 'تاريخ الميلاد',
    servicesAndResponsibilities: 'الخدمات والمسؤوليات',
    updateProfile: 'تحديث الملف الشخصي',
    theme: 'المظهر',
    default: 'الافتراضي',
    spiritual: 'روحاني',
    traditional: 'تراثي',
    modern: 'خدمي حديث',
    layout: 'التقسيم',
    topNav: 'شريط علوي',
    compact: 'مضغوط',
  },
  en: {
    churchName: 'Sunday School',
    churchSubName: 'St. George & St. Pachomius',
    dashboard: 'Dashboard',
    servants: 'Servants',
    attendance: 'Attendance',
    trips: 'Trips',
    settings: 'Settings',
    logout: 'Logout',
    agenda: 'Feasts Agenda',
    export: 'Export Data (CSV)',
    import: 'Import Data',
    profile: 'Profile',
    admin: 'Admin',
    priest: 'Priest',
    serviceLeader: 'Service Leader',
    servant: 'Servant',
    back: 'Back',
    save: 'Save',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    search: 'Search...',
    language: 'Language',
    darkMode: 'Dark Mode',
    readingMode: 'Reading Mode',
    fontSize: 'Font Size',
    fontFamily: 'Font Family',
    dateTimeSettings: 'Date & Time Settings',
    dateFormat: 'Date Format',
    timeFormat: 'Time Format',
    male: 'Male',
    female: 'Female',
    all: 'All',
    mass: 'Mass',
    service: 'Service',
    notes: 'Notes',
    birthDate: 'Birth Date',
    phone: 'Phone',
    address: 'Address',
    confession: 'Confession Father',
    father: 'Father',
    mother: 'Mother',
    job: 'Job',
    whatsapp: 'WhatsApp',
    facebook: 'Facebook',
    telegram: 'Telegram',
    instagram: 'Instagram',
    gmail: 'Gmail',
    landline: 'Landline',
    saveTrip: 'Save Trip',
    tripName: 'Trip Name',
    tripDate: 'Trip Date',
    tripPrice: 'Trip Price',
    bookings: 'Bookings',
    amount: 'Amount',
    total: 'Total',
    report: 'Report',
    monthly: 'Monthly',
    yearly: 'Yearly',
    month: 'Month',
    year: 'Year',
    noData: 'No Data',
    login: 'Login',
    register: 'Register',
    username: 'Username',
    password: 'Password',
    fullName: 'Full Name',
    showPassword: 'Show Password',
    authError: 'Auth Error',
    welcome: 'Welcome',
    copticDate: 'Coptic Date',
    gregorianDate: 'Gregorian Date',
    time: 'Time',
    services: 'Services',
    servantsList: 'Servants List',
    mlayka: 'Mlayka',
    ibtida2y: 'Primary',
    eadady: 'Middle School',
    thanawy: 'High School',
    shabab: 'Youth',
    birthdaysThisWeek: 'Birthdays This Week',
    today: 'Today!',
    servantsCount: 'Servants',
    addServant: 'Add Servant',
    reports: 'Reports',
    classStats: 'Class Stats',
    registerAttendance: 'Register Attendance',
    add: 'Add',
    searchByName: 'Search by name...',
    allBirthMonths: 'All Birth Months',
    noServants: 'No servants added yet in this class.',
    tripsFor: 'Trips for',
    addTrip: 'Add Trip',
    viewBookings: 'View Bookings',
    price: 'Price',
    general: 'General',
    currency: 'EGP',
    confirmDeleteTrip: 'Delete trip?',
    copticFeast: 'Coptic Feast',
    agendaTitle: 'Feasts & Events Agenda',
    loginButton: 'Login',
    registerButton: 'Register',
    noAccount: 'No account? Register now',
    haveAccount: 'Already have an account? Login',
    readingModeDesc: 'Optimize reading experience',
    fontColor: 'Font Color',
    fontColorDesc: 'Change primary font color',
    darkModeDesc: 'Change app appearance',
    small: 'Small',
    medium: 'Medium',
    large: 'Large',
    sans: 'Sans',
    serif: 'Serif',
    mono: 'Mono',
    h12: '12h',
    h24: '24h',
    totalCollected: 'Total Collected',
    totalRemaining: 'Total Remaining',
    selectServantToBook: 'Select servant to book',
    bookingsList: 'Bookings List',
    deletedServant: 'Deleted servant',
    remaining: 'Remaining',
    noBookings: 'No bookings yet',
    tripDayMessage: 'Today is the trip day! The list is ready.',
    saveAttendance: 'Save Attendance',
    backToList: 'Back to list',
    personalData: 'Personal Data',
    notSpecified: 'Not specified',
    call: 'Call',
    absenceWarningFather: 'Absence Warning (Father)',
    absenceWarningMother: 'Absence Warning (Mother)',
    whatsappFather: 'WhatsApp (Father)',
    whatsappMother: 'WhatsApp (Mother)',
    quickAttendance: 'Quick Attendance',
    attendMass: 'Attend Mass',
    attendService: 'Attend Service',
    tripBooking: 'Trip Booking',
    paid: 'Paid',
    servantsInService: 'Servants in your services',
    assignedServices: 'Assigned Services',
    editServantData: 'Edit Servant Data',
    addNewServant: 'Add New Servant',
    servantPhoto: 'Servant Photo',
    gender: 'Gender',
    fullNamePlaceholder: 'Full name (at least triple)',
    whatsappSameAsPhone: 'Same as phone',
    optional: 'Optional',
    telegramPlaceholder: 'Phone number or username',
    instagramPlaceholder: 'Link or username',
    gmailPlaceholder: 'Email address',
    captureCurrentLocation: 'Capture Current Location',
    locationCaptured: 'Location captured successfully',
    parentsData: 'Parents Data',
    fatherName: 'Father Name',
    fatherJob: 'Father Job',
    fatherPhone: 'Father Phone',
    fatherConfession: 'Father Confession',
    motherName: 'Mother Name',
    motherJob: 'Mother Job',
    motherPhone: 'Mother Phone',
    motherConfession: 'Mother Confession',
    servantNotes: 'Servant Notes',
    servantNotesPlaceholder: 'Add any additional notes here...',
    saveChanges: 'Save Changes',
    addServantToService: 'Add Servant to Service',
    select: 'Select',
    stage: 'Stage',
    allStages: 'All Stages',
    servantsCountLabel: 'Servants',
    backTitle: 'Back',
    inThisClass: 'in this class',
    noNumber: 'No number',
    enterAmountAlert: 'Please enter the amount',
    book: 'Book',
    noTripsAvailable: 'No trips available currently',
    fatherData: 'Father Data',
    motherData: 'Mother Data',
    nameLabel: 'Name',
    jobLabel: 'Job',
    notesLabel: 'Notes',
    confirmDeleteServant: 'Are you sure you want to delete this servant?',
    deleteServantPermanently: 'Delete Servant Permanently',
    adminRole: 'System Admin',
    priestRole: 'Priest',
    serviceLeaderRole: 'Service Leader',
    servantRole: 'Servant',
    fullNameLabel: 'Full Name',
    phoneNumberLabel: 'Phone Number',
    emailLabel: 'Email',
    whatsappLabel: 'WhatsApp',
    addressLabel: 'Address',
    birthDateLabel: 'Birth Date',
    servicesAndResponsibilities: 'Services and Responsibilities',
    updateProfile: 'Update Profile',
    theme: 'Theme',
    default: 'Default',
    spiritual: 'Spiritual',
    traditional: 'Traditional',
    modern: 'Modern',
    layout: 'Layout',
    topNav: 'Top Nav',
    compact: 'Compact',
  }
};

export const STORAGE_KEY = 'servant_app_v2';
export const USERS_STORAGE_KEY = 'servant_app_users_v1';

export const DEFAULT_ADMIN: User = {
  id: 'admin-id',
  username: 'admin',
  password: '@dmin123',
  role: 'admin',
  fullName: 'مدير النظام',
  birthDate: '1990-01-01',
  email: 'admin@church.com',
  phone: '0123456789',
  whatsapp: '0123456789',
  address: 'الكنيسة',
  assignments: []
};

export const SERVICE_STRUCTURE = {
  mlayka: { label: 'ملايكة', icon: 'Baby', color: 'text-pink-500', bg: 'bg-pink-50 dark:bg-pink-900/20', subServices: ['Baby', 'KG1', 'KG2'] },
  ibtida2y: { label: 'ابتدائي', icon: 'UserRound', color: 'text-blue-500', bg: 'bg-blue-50 dark:bg-blue-900/20', subServices: ['أولى', 'تانية', 'تالتة', 'رابعة', 'خامسة', 'سادسة'] },
  eadady: { label: 'إعدادي', icon: 'GraduationCap', color: 'text-orange-500', bg: 'bg-orange-50 dark:bg-orange-900/20', subServices: ['أولى', 'تانية', 'تالتة'] },
  thanawy: { label: 'ثانوي', icon: 'GraduationCap', color: 'text-emerald-500', bg: 'bg-emerald-50 dark:bg-emerald-900/20', subServices: ['أولى', 'تانية', 'تالتة'] },
  shabab: { label: 'شباب', icon: 'Users', color: 'text-purple-500', bg: 'bg-purple-50 dark:bg-purple-900/20', subServices: ['أولى كلية', 'تانية كلية', 'تالتة كلية', 'رابعة كلية', 'خامسة كلية', 'خريج'] }
};

export const COPTIC_HOLIDAYS = [
  { name: 'عيد الميلاد المجيد', enName: 'Christmas', date: '29 كيهك', enDate: '29 Kiahk', note: '7 يناير', enNote: 'Jan 7' },
  { name: 'عيد الغطاس المجيد', enName: 'Epiphany', date: '11 طوبة', enDate: '11 Toba', note: '19 يناير', enNote: 'Jan 19' },
  { name: 'عيد البشارة المجيد', enName: 'Annunciation', date: '29 برمهات', enDate: '29 Paremhat', note: '7 أبريل', enNote: 'Apr 7' },
  { name: 'أحد الشعانين', enName: 'Palm Sunday', date: 'متغير', enDate: 'Variable', note: 'أسبوع الآلام', enNote: 'Passion Week' },
  { name: 'عيد القيامة المجيد', enName: 'Easter', date: 'متغير', enDate: 'Variable', note: 'الفصح', enNote: 'Easter' },
  { name: 'عيد الصعود المجيد', enName: 'Ascension', date: 'متغير', enDate: 'Variable', note: '40 يوم بعد القيامة', enNote: '40 days after Easter' },
  { name: 'عيد العنصرة', enName: 'Pentecost', date: 'متغير', enDate: 'Variable', note: '50 يوم بعد القيامة', enNote: '50 days after Easter' },
  { name: 'عيد الرسل', enName: 'Apostles Feast', date: '5 أبيب', enDate: '5 Abib', note: '12 يوليو', enNote: 'July 12' },
  { name: 'عيد العذراء مريم', enName: 'St. Mary Feast', date: '16 مسرى', enDate: '16 Mesra', note: '22 أغسطس', enNote: 'Aug 22' },
  { name: 'عيد النيروز', enName: 'Nayrouz', date: '1 توت', enDate: '1 Tout', note: 'رأس السنة القبطية', enNote: 'Coptic New Year' },
  { name: 'عيد الصليب', enName: 'Cross Feast', date: '17 توت', enDate: '17 Tout', note: '27 سبتمبر', enNote: 'Sept 27' }
];
